import UserService from "@class/UserClass";
import { Prisma } from "@prisma/client";
import {
    UserCountProps,
    UserCountResponse,
    UserFindFirstProps,
    UserFindFirstResponse,
    UserFindManyProps,
    UserFindManyResponse,
    UserFindUniqueProps,
    UserFindUniqueResponse,
} from "@services/types";
import { cacheLifeApi, hashParamsForCacheKey } from "@utils/FetchConfig";
import { unstable_cacheLife as cacheLife, unstable_cacheTag as cacheTag } from "next/cache";

/**
 * # User Cached Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/cached/{{model}}Cached.hbs` as base template
 * - to generate cached function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Services ========== //

export const UserFindFirstCached = async <T extends Prisma.UserFindFirstArgs>(
    params: UserFindFirstProps<T>,
): Promise<UserFindFirstResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All user services
        "user",
        // All findFirst services
        "findFirst",
        // All user findFirst services
        "user-findFirst",
        // This specific services
        hashParamsForCacheKey("user-findFirst", params),
    );

    return await UserService.findFirst(params);
};

export const UserFindUniqueCached = async <T extends Prisma.UserFindUniqueArgs>(
    params: UserFindUniqueProps<T>,
): Promise<UserFindUniqueResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All user services
        "user",
        // All findUnique services
        "findUnique",
        // All user findUnique services
        "user-findUnique",
        // This specific services
        hashParamsForCacheKey("user-findUnique", params),
    );

    return await UserService.findUnique(params);
};

export const UserFindManyCached = async <T extends Prisma.UserFindManyArgs>(
    params: UserFindManyProps<T>,
): Promise<UserFindManyResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All user services
        "user",
        // All findMany services
        "findMany",
        // All user findMany services
        "user-findMany",
        // This specific services
        hashParamsForCacheKey("user-findMany", params),
    );

    return await UserService.findMany(params);
};

export const UserCountCached = async <T extends Prisma.UserCountArgs>(
    params: UserCountProps<T>,
): Promise<UserCountResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All user services
        "user",
        // All count services
        "count",
        // All user count services
        "user-count",
        // This specific services
        hashParamsForCacheKey("user-count", params),
    );

    return await UserService.count(params);
};
