services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres-dev
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5433:5432"
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 2s
            timeout: 1s
            retries: 30
            start_period: 10s

volumes:
    postgres-volume:
        name: postgres-volume
        driver: local
