import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import {
    AccountCountCached,
    AccountFindFirstCached,
    AccountFindManyCached,
    AccountFindUniqueCached,
} from "@services/cached";

/**
 * # Account Server Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/server/{{model}}Server.hbs` as base template
 * - to generate server function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type AccountFindFirstProps<T extends Prisma.AccountFindFirstArgs> = Prisma.SelectSubset<T, Prisma.AccountFindFirstArgs>;
type AccountFindFirstResponse<T extends Prisma.AccountFindFirstArgs> = GetResult<
    Prisma.$AccountPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type AccountFindUniqueProps<T extends Prisma.AccountFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.AccountFindUniqueArgs
>;
type AccountFindUniqueResponse<T extends Prisma.AccountFindUniqueArgs> = GetResult<
    Prisma.$AccountPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type AccountFindManyProps<T extends Prisma.AccountFindManyArgs> = Prisma.SelectSubset<T, Prisma.AccountFindManyArgs>;
type AccountFindManyResponse<T extends Prisma.AccountFindManyArgs> = GetResult<
    Prisma.$AccountPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type AccountCountProps<T extends Prisma.AccountCountArgs> = Prisma.SelectSubset<T, Prisma.AccountCountArgs>;
type AccountCountResponse<T extends Prisma.AccountCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.AccountCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Account Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const AccountFindFirstServer = async <T extends Prisma.AccountFindFirstArgs>(
    params: AccountFindFirstProps<T>,
): Promise<AccountFindFirstResponse<T>> => {
    return await AccountFindFirstCached(params);
};

/**
 * ## Account Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const AccountFindUniqueServer = async <T extends Prisma.AccountFindUniqueArgs>(
    params: AccountFindUniqueProps<T>,
): Promise<AccountFindUniqueResponse<T>> => {
    return await AccountFindUniqueCached(params);
};

/**
 * ## Account Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const AccountFindManyServer = async <T extends Prisma.AccountFindManyArgs>(
    params: AccountFindManyProps<T>,
): Promise<AccountFindManyResponse<T>> => {
    return await AccountFindManyCached(params);
};

/**
 * ## Account Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const AccountCountServer = async <T extends Prisma.AccountCountArgs>(
    params: AccountCountProps<T>,
): Promise<AccountCountResponse<T>> => {
    return await AccountCountCached(params);
};
