"use server";

import SessionService from "@class/SessionClass";
// import { requiresSafeMessage } from "@permissions/requiresSafeMessage";
import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";

/**
 * # Session Action Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/actions/{{model}}Action.hbs` as base template
 * - to generate server actions files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Create
type SessionCreateProps<T extends Prisma.SessionCreateArgs> = Prisma.SelectSubset<T, Prisma.SessionCreateArgs>;
type SessionCreateResponse<T extends Prisma.SessionCreateArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

// Upsert
type SessionUpsertProps<T extends Prisma.SessionUpsertArgs> = Prisma.SelectSubset<T, Prisma.SessionUpsertArgs>;
type SessionUpsertResponse<T extends Prisma.SessionUpsertArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

// Update
type SessionUpdateProps<T extends Prisma.SessionUpdateArgs> = Prisma.SelectSubset<T, Prisma.SessionUpdateArgs>;
type SessionUpdateResponse<T extends Prisma.SessionUpdateArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

// Delete
type SessionDeleteProps<T extends Prisma.SessionDeleteArgs> = Prisma.SelectSubset<T, Prisma.SessionDeleteArgs>;
type SessionDeleteResponse<T extends Prisma.SessionDeleteArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

// Create Many
type SessionCreateManyProps<T extends Prisma.SessionCreateManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.SessionCreateManyArgs
>;
type SessionCreateManyResponse = Prisma.BatchPayload;

// Update Many
type SessionUpdateManyProps<T extends Prisma.SessionUpdateManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.SessionUpdateManyArgs
>;
type SessionUpdateManyResponse = Prisma.BatchPayload;

// Delete Many
type SessionDeleteManyProps<T extends Prisma.SessionDeleteManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.SessionDeleteManyArgs
>;
type SessionDeleteManyResponse = Prisma.BatchPayload;

// Find First
type SessionFindFirstProps<T extends Prisma.SessionFindFirstArgs> = Prisma.SelectSubset<T, Prisma.SessionFindFirstArgs>;
type SessionFindFirstResponse<T extends Prisma.SessionFindFirstArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type SessionFindUniqueProps<T extends Prisma.SessionFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.SessionFindUniqueArgs
>;
type SessionFindUniqueResponse<T extends Prisma.SessionFindUniqueArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type SessionFindManyProps<T extends Prisma.SessionFindManyArgs> = Prisma.SelectSubset<T, Prisma.SessionFindManyArgs>;
type SessionFindManyResponse<T extends Prisma.SessionFindManyArgs> = GetResult<
    Prisma.$SessionPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type SessionCountProps<T extends Prisma.SessionCountArgs> = Prisma.SelectSubset<T, Prisma.SessionCountArgs>;
type SessionCountResponse<T extends Prisma.SessionCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.SessionCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Session Create (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionCreateAction = async <T extends Prisma.SessionCreateArgs>(
    props: SessionCreateProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionCreateResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionCreateAction", "Session", "create");
    return await SessionService.create(props);
};

/**
 * ## Session Upsert (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionUpsertAction = async <T extends Prisma.SessionUpsertArgs>(
    props: SessionUpsertProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionUpsertResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionUpsertAction", "Session", "upsert");
    return await SessionService.upsert(props);
};

/**
 * ## Session Update (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionUpdateAction = async <T extends Prisma.SessionUpdateArgs>(
    props: SessionUpdateProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionUpdateResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionUpdateAction", "Session", "update");
    return await SessionService.update(props);
};

/**
 * ## Session Delete (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionDeleteAction = async <T extends Prisma.SessionDeleteArgs>(
    props: SessionDeleteProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionDeleteResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionDeleteAction", "Session", "delete");
    return await SessionService.delete(props);
};

/**
 * ## Session Create Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionCreateManyAction = async <T extends Prisma.SessionCreateManyArgs>(
    props: SessionCreateManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionCreateManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionCreateManyAction", "Session", "createMany");
    return await SessionService.createMany(props);
};

/**
 * ## Session Update Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionUpdateManyAction = async <T extends Prisma.SessionUpdateManyArgs>(
    props: SessionUpdateManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionUpdateManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionUpdateManyAction", "Session", "updateMany");
    return await SessionService.updateMany(props);
};

/**
 * ## Session Delete Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const SessionDeleteManyAction = async <T extends Prisma.SessionDeleteManyArgs>(
    props: SessionDeleteManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionDeleteManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionDeleteManyAction", "Session", "deleteMany");
    return await SessionService.deleteMany(props);
};

/**
 * ## Session Find First (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const SessionFindFirstAction = async <T extends Prisma.SessionFindFirstArgs>(
    props: SessionFindFirstProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionFindFirstResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionFindFirstAction", "Session", "findFirst");
    return await SessionService.findFirst(props);
};

/**
 * ## Session Find Unique (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const SessionFindUniqueAction = async <T extends Prisma.SessionFindUniqueArgs>(
    props: SessionFindUniqueProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionFindUniqueResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionFindUniqueAction", "Session", "findUnique");
    return await SessionService.findUnique(props);
};

/**
 * ## Session Find Many (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const SessionFindManyAction = async <T extends Prisma.SessionFindManyArgs>(
    props: SessionFindManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionFindManyResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionFindManyAction", "Session", "findMany");
    return await SessionService.findMany(props);
};

/**
 * ## Session Count (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const SessionCountAction = async <T extends Prisma.SessionCountArgs>(
    props: SessionCountProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<SessionCountResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "SessionCountAction", "Session", "count");
    return await SessionService.count(props);
};
