"use server";

import UserService from "@class/UserClass";
// import { requiresSafeMessage } from "@permissions/requiresSafeMessage";
import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";

/**
 * # User Action Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/actions/{{model}}Action.hbs` as base template
 * - to generate server actions files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Create
type UserCreateProps<T extends Prisma.UserCreateArgs> = Prisma.SelectSubset<T, Prisma.UserCreateArgs>;
type UserCreateResponse<T extends Prisma.UserCreateArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

// Upsert
type UserUpsertProps<T extends Prisma.UserUpsertArgs> = Prisma.SelectSubset<T, Prisma.UserUpsertArgs>;
type UserUpsertResponse<T extends Prisma.UserUpsertArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

// Update
type UserUpdateProps<T extends Prisma.UserUpdateArgs> = Prisma.SelectSubset<T, Prisma.UserUpdateArgs>;
type UserUpdateResponse<T extends Prisma.UserUpdateArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

// Delete
type UserDeleteProps<T extends Prisma.UserDeleteArgs> = Prisma.SelectSubset<T, Prisma.UserDeleteArgs>;
type UserDeleteResponse<T extends Prisma.UserDeleteArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

// Create Many
type UserCreateManyProps<T extends Prisma.UserCreateManyArgs> = Prisma.SelectSubset<T, Prisma.UserCreateManyArgs>;
type UserCreateManyResponse = Prisma.BatchPayload;

// Update Many
type UserUpdateManyProps<T extends Prisma.UserUpdateManyArgs> = Prisma.SelectSubset<T, Prisma.UserUpdateManyArgs>;
type UserUpdateManyResponse = Prisma.BatchPayload;

// Delete Many
type UserDeleteManyProps<T extends Prisma.UserDeleteManyArgs> = Prisma.SelectSubset<T, Prisma.UserDeleteManyArgs>;
type UserDeleteManyResponse = Prisma.BatchPayload;

// Find First
type UserFindFirstProps<T extends Prisma.UserFindFirstArgs> = Prisma.SelectSubset<T, Prisma.UserFindFirstArgs>;
type UserFindFirstResponse<T extends Prisma.UserFindFirstArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type UserFindUniqueProps<T extends Prisma.UserFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.UserFindUniqueArgs>;
type UserFindUniqueResponse<T extends Prisma.UserFindUniqueArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type UserFindManyProps<T extends Prisma.UserFindManyArgs> = Prisma.SelectSubset<T, Prisma.UserFindManyArgs>;
type UserFindManyResponse<T extends Prisma.UserFindManyArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type UserCountProps<T extends Prisma.UserCountArgs> = Prisma.SelectSubset<T, Prisma.UserCountArgs>;
type UserCountResponse<T extends Prisma.UserCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.UserCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## User Create (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserCreateAction = async <T extends Prisma.UserCreateArgs>(
    props: UserCreateProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserCreateResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserCreateAction", "User", "create");
    return await UserService.create(props);
};

/**
 * ## User Upsert (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserUpsertAction = async <T extends Prisma.UserUpsertArgs>(
    props: UserUpsertProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserUpsertResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserUpsertAction", "User", "upsert");
    return await UserService.upsert(props);
};

/**
 * ## User Update (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserUpdateAction = async <T extends Prisma.UserUpdateArgs>(
    props: UserUpdateProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserUpdateResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserUpdateAction", "User", "update");
    return await UserService.update(props);
};

/**
 * ## User Delete (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserDeleteAction = async <T extends Prisma.UserDeleteArgs>(
    props: UserDeleteProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserDeleteResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserDeleteAction", "User", "delete");
    return await UserService.delete(props);
};

/**
 * ## User Create Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserCreateManyAction = async <T extends Prisma.UserCreateManyArgs>(
    props: UserCreateManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserCreateManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "UserCreateManyAction", "User", "createMany");
    return await UserService.createMany(props);
};

/**
 * ## User Update Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserUpdateManyAction = async <T extends Prisma.UserUpdateManyArgs>(
    props: UserUpdateManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserUpdateManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "UserUpdateManyAction", "User", "updateMany");
    return await UserService.updateMany(props);
};

/**
 * ## User Delete Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const UserDeleteManyAction = async <T extends Prisma.UserDeleteManyArgs>(
    props: UserDeleteManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserDeleteManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "UserDeleteManyAction", "User", "deleteMany");
    return await UserService.deleteMany(props);
};

/**
 * ## User Find First (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const UserFindFirstAction = async <T extends Prisma.UserFindFirstArgs>(
    props: UserFindFirstProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserFindFirstResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserFindFirstAction", "User", "findFirst");
    return await UserService.findFirst(props);
};

/**
 * ## User Find Unique (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const UserFindUniqueAction = async <T extends Prisma.UserFindUniqueArgs>(
    props: UserFindUniqueProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserFindUniqueResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserFindUniqueAction", "User", "findUnique");
    return await UserService.findUnique(props);
};

/**
 * ## User Find Many (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const UserFindManyAction = async <T extends Prisma.UserFindManyArgs>(
    props: UserFindManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserFindManyResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserFindManyAction", "User", "findMany");
    return await UserService.findMany(props);
};

/**
 * ## User Count (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const UserCountAction = async <T extends Prisma.UserCountArgs>(
    props: UserCountProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<UserCountResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "UserCountAction", "User", "count");
    return await UserService.count(props);
};
