import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import { UserCountCached, UserFindFirstCached, UserFindManyCached, UserFindUniqueCached } from "@services/cached";
import { ResponseFormat, parseAndDecodeParams } from "@utils/FetchConfig";
import { NextRequest, NextResponse } from "next/server";

/**
 * # User Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type UserFindFirstProps<T extends Prisma.UserFindFirstArgs> = Prisma.SelectSubset<T, Prisma.UserFindFirstArgs>;
type UserFindFirstResponse<T extends Prisma.UserFindFirstArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type UserFindUniqueProps<T extends Prisma.UserFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.UserFindUniqueArgs>;
type UserFindUniqueResponse<T extends Prisma.UserFindUniqueArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type UserFindManyProps<T extends Prisma.UserFindManyArgs> = Prisma.SelectSubset<T, Prisma.UserFindManyArgs>;
type UserFindManyResponse<T extends Prisma.UserFindManyArgs> = GetResult<
    Prisma.$UserPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type UserCountProps<T extends Prisma.UserCountArgs> = Prisma.SelectSubset<T, Prisma.UserCountArgs>;
type UserCountResponse<T extends Prisma.UserCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.UserCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type UserRoutes<Input> = {
    "/internal/user/findFirst": <T extends Prisma.UserFindFirstArgs>() => {
        params: UserFindFirstProps<T>;
        response: UserFindFirstResponse<Input extends UserFindFirstProps<T> ? Input : never>;
    };
    "/internal/user/findUnique": <T extends Prisma.UserFindUniqueArgs>() => {
        params: UserFindUniqueProps<T>;
        response: UserFindUniqueResponse<Input extends UserFindUniqueProps<T> ? Input : never>;
    };
    "/internal/user/findMany": <T extends Prisma.UserFindManyArgs>() => {
        params: UserFindManyProps<T>;
        response: UserFindManyResponse<Input extends UserFindManyProps<T> ? Input : never>;
    };
    "/internal/user/count": <T extends Prisma.UserCountArgs>() => {
        params: UserCountProps<T>;
        response: UserCountResponse<Input extends UserCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const UserFindFirstApi = async <T extends Prisma.UserFindFirstArgs>(
    request: NextRequest,
): RouteResponse<UserFindFirstResponse<T>> => {
    try {
        const params: UserFindFirstProps<T> = parseAndDecodeParams(request);
        const response: UserFindFirstResponse<T> = await UserFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const UserFindUniqueApi = async <T extends Prisma.UserFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<UserFindUniqueResponse<T>> => {
    try {
        const params: UserFindUniqueProps<T> = parseAndDecodeParams(request);
        const response: UserFindUniqueResponse<T> = await UserFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const UserFindManyApi = async <T extends Prisma.UserFindManyArgs>(
    request: NextRequest,
): RouteResponse<UserFindManyResponse<T>> => {
    try {
        const params: UserFindManyProps<T> = parseAndDecodeParams(request);
        const response: UserFindManyResponse<T> = await UserFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const UserCountApi = async <T extends Prisma.UserCountArgs>(
    request: NextRequest,
): RouteResponse<UserCountResponse<T>> => {
    try {
        const params: UserCountProps<T> = parseAndDecodeParams(request);
        const response: UserCountResponse<T> = await UserCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
